// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';

const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvdWpsaHNnc2V5ZHhjcG9sZWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjk4MzgsImV4cCI6MjA2ODg0NTgzOH0.PjwqMIbAm4Zsqn3c7c0I1yR6ij1uBVJLZsVLVD9u4C8";


  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});