project_id = "eoujlhsgseydxcpoledz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54329
poll_max_age = 30
poll_max_rows = 200
max_depth = 12
max_rows = 200

[functions.image-proxy]
verify_jwt = false

[functions.cocart-api]
verify_jwt = false

[functions.woocommerce-api]
verify_jwt = false

[functions.wordpress-api]
verify_jwt = false

[functions.wordpress-auth]
verify_jwt = false