
-- Insert the complete Sport collection with 9 references as shown in the image
INSERT INTO products (
  name, slug, description, price, original_price, category, collection, 
  color, usage, genre, features, specifications, is_popular, in_stock, images
) VALUES 
-- Music Shield variants (row 1)
(
  'Music Shield Noir',
  'music-shield-noir',
  'Lunettes de sport avec audio intégré - Modèle Noir',
  249,
  NULL,
  'sport',
  'sport',
  ARRAY['noir'],
  'sport',
  'mixte',
  ARRAY['Audio intégré', 'Branches ajustables', 'Verres performants', 'Design sport'],
  '{"autonomie": "12 heures", "audio": "Stéréo haute qualité", "résistance": "IPX4", "poids": "32g"}',
  true,
  true,
  ARRAY['/placeholder.svg']
),
(
  'Music Shield Rouge',
  'music-shield-rouge',
  'Lunettes de sport avec audio intégré - Modèle Rouge',
  249,
  NULL,
  'sport',
  'sport',
  ARRAY['rouge'],
  'sport',
  'mixte',
  ARRAY['Audio intégré', 'Branches ajustables', 'Verres performants', 'Design sport'],
  '{"autonomie": "12 heures", "audio": "Stéréo haute qualité", "résistance": "IPX4", "poids": "32g"}',
  true,
  true,
  ARRAY['/placeholder.svg']
),
(
  'Music Shield Bleu',
  'music-shield-bleu',
  'Lunettes de sport avec audio intégré - Modèle Bleu',
  249,
  NULL,
  'sport',
  'sport',
  ARRAY['bleu'],
  'sport',
  'mixte',
  ARRAY['Audio intégré', 'Branches ajustables', 'Verres performants', 'Design sport'],
  '{"autonomie": "12 heures", "audio": "Stéréo haute qualité", "résistance": "IPX4", "poids": "32g"}',
  true,
  true,
  ARRAY['/placeholder.svg']
),
-- Falcon variants (row 2)
(
  'Falcon Noir',
  'falcon-noir',
  'Lunettes sport avec ajustement automatique de la teinte - Modèle Noir',
  199,
  NULL,
  'sport',
  'sport',
  ARRAY['noir'],
  'sport',
  'mixte',
  ARRAY['Teinte automatique', 'Design enveloppant', 'Performance', 'Anti-éblouissement'],
  '{"teinte": "Ajustement automatique", "protection": "UV400", "matériau": "TR90 sport", "poids": "28g"}',
  false,
  true,
  ARRAY['/placeholder.svg']
),
(
  'Falcon Fumé',
  'falcon-fume',
  'Lunettes sport avec ajustement automatique de la teinte - Modèle Fumé',
  199,
  NULL,
  'sport',
  'sport',
  ARRAY['fumé'],
  'sport',
  'mixte',
  ARRAY['Teinte automatique', 'Design enveloppant', 'Performance', 'Anti-éblouissement'],
  '{"teinte": "Ajustement automatique", "protection": "UV400", "matériau": "TR90 sport", "poids": "28g"}',
  false,
  true,
  ARRAY['/placeholder.svg']
),
(
  'Falcon Iridescent',
  'falcon-iridescent',
  'Lunettes sport avec ajustement automatique de la teinte - Modèle Iridescent',
  199,
  NULL,
  'sport',
  'sport',
  ARRAY['iridescent'],
  'sport',
  'mixte',
  ARRAY['Teinte automatique', 'Design enveloppant', 'Performance', 'Anti-éblouissement'],
  '{"teinte": "Ajustement automatique", "protection": "UV400", "matériau": "TR90 sport", "poids": "28g"}',
  false,
  true,
  ARRAY['/placeholder.svg']
),
-- Shield variants (row 3)
(
  'Shield Rouge',
  'shield-rouge',
  'Nouvelle génération de lunettes de sport avec verres double teinte - Modèle Rouge',
  199,
  159,
  'sport',
  'sport',
  ARRAY['rouge'],
  'sport',
  'mixte',
  ARRAY['Verres double teinte', 'Nouvelle génération', 'Protection avancée', 'Design sport'],
  '{"verres": "Double teinte (dual-tint)", "protection": "UV400+", "technologie": "Nouvelle génération", "poids": "30g"}',
  false,
  true,
  ARRAY['/placeholder.svg']
),
(
  'Shield Violet',
  'shield-violet',
  'Nouvelle génération de lunettes de sport avec verres double teinte - Modèle Violet',
  199,
  159,
  'sport',
  'sport',
  ARRAY['violet'],
  'sport',
  'mixte',
  ARRAY['Verres double teinte', 'Nouvelle génération', 'Protection avancée', 'Design sport'],
  '{"verres": "Double teinte (dual-tint)", "protection": "UV400+", "technologie": "Nouvelle génération", "poids": "30g"}',
  false,
  true,
  ARRAY['/placeholder.svg']
),
(
  'Shield Orange',
  'shield-orange',
  'Nouvelle génération de lunettes de sport avec verres double teinte - Modèle Orange',
  199,
  159,
  'sport',
  'sport',
  ARRAY['orange'],
  'sport',
  'mixte',
  ARRAY['Verres double teinte', 'Nouvelle génération', 'Protection avancée', 'Design sport'],
  '{"verres": "Double teinte (dual-tint)", "protection": "UV400+", "technologie": "Nouvelle génération", "poids": "30g"}',
  false,
  true,
  ARRAY['/placeholder.svg']
);
