// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggjfuflwmnphnyyfbunr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnamZ1Zmx3bW5waG55eWZidW5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzA3NDQsImV4cCI6MjA2NjYwNjc0NH0.s0vn5CNcsh_3I6bcuJY5mSlDjNH3-MalPJvAQnY_kNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);