// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Utilisation des variables d'environnement pour la connexion Supabase
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_KEY as string;

// Vérification que les variables d'environnement sont bien définies
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn("ATTENTION: Les variables d'environnement Supabase ne sont pas toutes définies.");
  console.warn("Assurez-vous d'avoir VITE_SUPABASE_URL et VITE_SUPABASE_KEY dans votre fichier .env");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);