name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  # Permet de lancer manuellement le workflow depuis l'interface GitHub
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint code
        run: npm run lint
      
      - name: Build project
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
      
      # Si vous ajoutez des tests plus tard
      # - name: Run tests
      #   run: npm test
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/
          retention-days: 7
  
  # Job de déploiement sur Coolify (uniquement pour les pushs sur main)
  deploy-to-coolify:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist
      
      - name: Deploy to Coolify
        run: |
          # Utilisez le webhook Coolify ou l'API pour déclencher un déploiement
          # Exemple avec curl et un webhook:
          if [ -n "${{ secrets.COOLIFY_WEBHOOK_URL }}" ]; then
            curl -X POST ${{ secrets.COOLIFY_WEBHOOK_URL }} \
              -H "Content-Type: application/json" \
              -d '{"ref": "${{ github.ref }}", "commit": "${{ github.sha }}"}'  
          else
            echo "Attention: COOLIFY_WEBHOOK_URL n'est pas configuré dans les secrets GitHub"
            exit 1
          fi
        # Note: Vous devrez configurer COOLIFY_WEBHOOK_URL dans les secrets GitHub
        # Vous pouvez également utiliser d'autres méthodes de déploiement selon votre configuration Coolify
